language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libatk1.0-dev
  - sudo apt-get install -y libpango1.0-dev
  - sudo apt-get install -y libgtk-3-dev
